const content = document.querySelector('.content');
export const buttonEdit = content.querySelector('.button-icon_action_edit');
export const username = content.querySelector('.profile__username');
export const formEdit = document.forms.edit;
export const inputUsername = formEdit.elements.username
export const inputUserJob = formEdit.elements.job
export const gallery = document.querySelector('.gallery__list')
export const buttonAdd = content.querySelector('.button-icon_action_add');
export const formAdd = document.forms.add
export const fullWidthImg = document.querySelector('.full-width__image');
export const fullWidthCaption =  document.querySelector('.full-width__caption')